name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Update Node.js version to match your project's requirement

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build-android

      - name: Deploy Frontend (Optional)
        # You can add steps here to deploy the frontend (e.g., to S3, Firebase, or Vercel).
        run: echo "Deploying Frontend..."
