name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Deploy Backend (Optional)
        # Add deployment step if needed (e.g., deploy to AWS, Heroku, or similar)
        run: echo "Deploying Backend..."
